const { DataTypes } = require('sequelize');
const sequelize = require('../config/database');

const Validation = sequelize.define('Validation', {
  id: { type: DataTypes.INTEGER, primaryKey: true, autoIncrement: true },
  ideaName: { type: DataTypes.STRING, allowNull: false },
  ideaDescription: { type: DataTypes.TEXT },
  appCategory: { type: DataTypes.STRING },
  appType: { type: DataTypes.ENUM('mobile_app', 'website', 'web_app', 'marketplace', 'saas', 'platform') },
  businessModel: { type: DataTypes.ENUM('b2b', 'b2c', 'b2b2c', 'internal', 'marketplace') },
  ideaNovelty: { type: DataTypes.ENUM('new', 'improvement') },
  targetAudience: { type: DataTypes.STRING },
  audienceScope: { type: DataTypes.ENUM('local', 'national', 'global') },
  ageGroup: { type: DataTypes.STRING },
  userType: { type: DataTypes.STRING },
  usageFrequency: { type: DataTypes.ENUM('daily', 'weekly', 'monthly', 'occasionally', 'one_time') },
  painLevel: { type: DataTypes.ENUM('low', 'medium', 'high', 'urgent') },
  problemDescription: { type: DataTypes.TEXT },
  currentSolution: { type: DataTypes.TEXT },
  problemConsequence: { type: DataTypes.TEXT },
  spokenToUsers: { type: DataTypes.BOOLEAN, defaultValue: false },
  hasUserFeedback: { type: DataTypes.BOOLEAN, defaultValue: false },
  hasEarlyCustomers: { type: DataTypes.BOOLEAN, defaultValue: false },
  problemProven: { type: DataTypes.BOOLEAN, defaultValue: false },
  hasCompetitors: { type: DataTypes.BOOLEAN, defaultValue: false },
  competitorNames: { type: DataTypes.TEXT },
  differentiation: { type: DataTypes.TEXT },
  competitorStatus: { type: DataTypes.ENUM('none', 'few', 'many', 'strong', 'not_researched') },
  marketType: { type: DataTypes.ENUM('existing', 'new') },
  monetizationModel: { type: DataTypes.STRING },
  monetizationTiming: { type: DataTypes.ENUM('mvp', 'later') },
  launchLocation: { type: DataTypes.STRING },
  launchScope: { type: DataTypes.ENUM('city', 'state', 'country', 'multi_country', 'global') },
  hasLocalRequirements: { type: DataTypes.BOOLEAN, defaultValue: false },
  priceSensitive: { type: DataTypes.BOOLEAN, defaultValue: false },
  hasMarketAccess: { type: DataTypes.BOOLEAN, defaultValue: false },
  mvpFeatures: { type: DataTypes.JSON },
  userRoles: { type: DataTypes.JSON },
  needsAdminPanel: { type: DataTypes.BOOLEAN, defaultValue: false },
  needsPayment: { type: DataTypes.BOOLEAN, defaultValue: false },
  needsChat: { type: DataTypes.BOOLEAN, defaultValue: false },
  needsLocation: { type: DataTypes.BOOLEAN, defaultValue: false },
  needsAI: { type: DataTypes.BOOLEAN, defaultValue: false },
  needsIntegrations: { type: DataTypes.BOOLEAN, defaultValue: false },
  platformNeeds: { type: DataTypes.STRING },
  ideaClarity: { type: DataTypes.INTEGER },
  marketRisk: { type: DataTypes.INTEGER },
  mvpFeasibility: { type: DataTypes.INTEGER },
  monetizationFit: { type: DataTypes.INTEGER },
  developmentComplexity: { type: DataTypes.INTEGER },
  overallScore: { type: DataTypes.INTEGER },
  resultType: { type: DataTypes.ENUM('ready_for_mvp', 'needs_validation', 'too_broad', 'high_risk', 'strong_complex') },
  recommendedMvp: { type: DataTypes.TEXT },
  featuresToAvoid: { type: DataTypes.TEXT },
  suggestedTech: { type: DataTypes.TEXT },
  strengths: { type: DataTypes.TEXT },
  weaknesses: { type: DataTypes.TEXT },
}, {
  tableName: 'validations',
  timestamps: true,
  underscored: true,
});

module.exports = Validation;
