const ValidationResource = {
  single: (v) => ({
    id: v.id,
    ideaName: v.ideaName,
    ideaDescription: v.ideaDescription,
    appCategory: v.appCategory,
    appType: v.appType,
    businessModel: v.businessModel,
    ideaNovelty: v.ideaNovelty,
    targetAudience: v.targetAudience,
    audienceScope: v.audienceScope,
    ageGroup: v.ageGroup,
    userType: v.userType,
    usageFrequency: v.usageFrequency,
    painLevel: v.painLevel,
    problemDescription: v.problemDescription,
    currentSolution: v.currentSolution,
    problemConsequence: v.problemConsequence,
    spokenToUsers: v.spokenToUsers,
    hasUserFeedback: v.hasUserFeedback,
    hasEarlyCustomers: v.hasEarlyCustomers,
    problemProven: v.problemProven,
    hasCompetitors: v.hasCompetitors,
    competitorNames: v.competitorNames,
    differentiation: v.differentiation,
    competitorStatus: v.competitorStatus,
    marketType: v.marketType,
    monetizationModel: v.monetizationModel,
    monetizationTiming: v.monetizationTiming,
    launchLocation: v.launchLocation,
    launchScope: v.launchScope,
    hasLocalRequirements: v.hasLocalRequirements,
    priceSensitive: v.priceSensitive,
    hasMarketAccess: v.hasMarketAccess,
    mvpFeatures: v.mvpFeatures,
    userRoles: v.userRoles,
    needsAdminPanel: v.needsAdminPanel,
    needsPayment: v.needsPayment,
    needsChat: v.needsChat,
    needsLocation: v.needsLocation,
    needsAI: v.needsAI,
    needsIntegrations: v.needsIntegrations,
    platformNeeds: v.platformNeeds,
    ideaClarity: v.ideaClarity,
    marketRisk: v.marketRisk,
    mvpFeasibility: v.mvpFeasibility,
    monetizationFit: v.monetizationFit,
    developmentComplexity: v.developmentComplexity,
    overallScore: v.overallScore,
    resultType: v.resultType,
    recommendedMvp: v.recommendedMvp,
    featuresToAvoid: v.featuresToAvoid,
    suggestedTech: v.suggestedTech,
    strengths: v.strengths,
    weaknesses: v.weaknesses,
    createdAt: v.createdAt,
  }),

  list: (validations) => validations.map(ValidationResource.single),
};

module.exports = ValidationResource;
